WHENEVER SQLERROR CONTINUE

DELETE  FROM SEC_TRUSTEDSERVER WHERE DESCRIPTION IN ('Real Condition Mobile Web', 'Real Condition Mobile Native');

INSERT INTO SMS.SEC_TRUSTEDSERVER (
   CLIENT_ID, DESCRIPTION, 
   CERT_SERIALNUM, NETWORK_TYPE, 
   REFERRAL_URL, AUTHENTICATION_METHOD,
   ACTIVE, CREATEDBY,  
   UPDATEDBY, SINGLESIGNON_ENABLED, SSO_SECRETKEY,
   SSO_SOLUTION, 
   SSO_CIPHER_MODE, DELEGATOR_USER_ID, SCOPE) 
VALUES ( 
 -1/* CLIENT_ID */,
 'Real Condition Mobile Web'/* DESCRIPTION */,
 '{DFA75CBD-C45D-4D55-8951-987E18C19715}'/* CERT_SERIALNUM */,
 'EXTERNAL'/* NETWORK_TYPE */,
 'http://localhost:8100/tabs/tab1'/* REFERRAL_URL */,
 2/* AUTHENTICATION_METHOD */,
 1/* ACTIVE */,
 'IT'/* CREATEDBY */,
 'IT'/* UPDATEDBY */,
 'Y'/* SINGLESIGNON_ENABLED */,
 'Welcome1'/* SSO_SECREKEY */,
 'OAUTH2'/* SSO_SOLUTION */,
 'N'/* SSO_CIPHER_MODE */,
 100/* DELEGATOR_USER_ID */,
 'BGIS.REALCONDITION'/* SCOPE */ );
 INSERT INTO SMS.SEC_TRUSTEDSERVER (
   CLIENT_ID, DESCRIPTION, 
   CERT_SERIALNUM, NETWORK_TYPE, 
   REFERRAL_URL, AUTHENTICATION_METHOD,
   ACTIVE, CREATEDBY,  
   UPDATEDBY, SINGLESIGNON_ENABLED, SSO_SECRETKEY,
   SSO_SOLUTION, 
   SSO_CIPHER_MODE, DELEGATOR_USER_ID, SCOPE) 
VALUES ( 
 -1/* CLIENT_ID */,
 'Real Condition Mobile Native'/* DESCRIPTION */,
 '{186B1ACD-248A-4CE3-8B06-FEAB96E4C678}'/* CERT_SERIALNUM */,
 'EXTERNAL'/* NETWORK_TYPE */,
 'com.bgis.rcmobile://bgis.rcmobile'/* REFERRAL_URL */,
 2/* AUTHENTICATION_METHOD */,
 1/* ACTIVE */,
 'IT'/* CREATEDBY */,
 'IT'/* UPDATEDBY */,
 'Y'/* SINGLESIGNON_ENABLED */,
 'Welcome1'/* SSO_SECREKEY */,
 'OAUTH2'/* SSO_SOLUTION */,
 'N'/* SSO_CIPHER_MODE */,
 100/* DELEGATOR_USER_ID */,
 'BGIS.REALCONDITION'/* SCOPE */ );
COMMIT;
/
